version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    user: 1000:1000
    ports:
      - 127.0.0.1:9666:9666
    environment:
      - "REALDEBRID_TOKEN="
      - "CNL_URL="
