name: Docker AMD64 Build

on:
  repository_dispatch:
    types: [build-docker-amd64]

jobs:
  docker-amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository name
        run: |
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO=${REPO}" >> $GITHUB_ENV
          VERSION="${{ github.event.client_payload.version }}"
          VERSION_NO_V="${VERSION#v}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "VERSION_NO_V=${VERSION_NO_V}" >> $GITHUB_ENV

      - name: Build and push Docker image (AMD64)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ env.REPO }}:${{ env.VERSION }}-amd64
            ghcr.io/${{ env.REPO }}:${{ env.VERSION_NO_V }}-amd64
            ghcr.io/${{ env.REPO }}:latest-amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Notify manifest builder
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: docker-amd64-complete
          client-payload: '{"version": "${{ env.VERSION }}", "status": "success"}'