name: Docker ARM64 Build

on:
  repository_dispatch:
    types: [build-docker-arm64]

jobs:
  docker-arm64:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository name
        run: |
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO=${REPO}" >> $GITHUB_ENV
          VERSION="${{ github.event.client_payload.version }}"
          VERSION_NO_V="${VERSION#v}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "VERSION_NO_V=${VERSION_NO_V}" >> $GITHUB_ENV

      - name: Build and push Docker image (ARM64)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: |
            ghcr.io/${{ env.REPO }}:${{ env.VERSION }}-arm64
            ghcr.io/${{ env.REPO }}:${{ env.VERSION_NO_V }}-arm64
            ghcr.io/${{ env.REPO }}:latest-arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update build status
        run: |
          # Create the status directory if it doesn't exist
          mkdir -p /tmp/clickndebrid-docker-builds
          
          # Mark ARM64 build as complete
          ARM64_FILE="/tmp/clickndebrid-docker-builds/ARM64_DONE"
          echo "${{ env.VERSION }}" > "$ARM64_FILE"
          echo "Marked ARM64 build as complete for version ${{ env.VERSION }}"
          
          # Log status for debugging
          if [ -f "$ARM64_FILE" ]; then
            echo "ARM64 status file exists and contains: $(cat $ARM64_FILE)"
          else
            echo "Failed to create ARM64 status file"
          fi
