name: Docker AMD64 Build

on:
  repository_dispatch:
    types: [build-docker-amd64]

jobs:
  docker-amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository name
        run: |
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO=${REPO}" >> $GITHUB_ENV
          VERSION="${{ github.event.client_payload.version }}"
          VERSION_NO_V="${VERSION#v}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "VERSION_NO_V=${VERSION_NO_V}" >> $GITHUB_ENV

      - name: Build and push Docker image (AMD64)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ env.REPO }}:${{ env.VERSION }}-amd64
            ghcr.io/${{ env.REPO }}:${{ env.VERSION_NO_V }}-amd64
            ghcr.io/${{ env.REPO }}:latest-amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update build status
        run: |
          # Create the status directory if it doesn't exist
          mkdir -p /tmp/clickndebrid-docker-builds
          
          # Mark AMD64 build as complete
          AMD64_FILE="/tmp/clickndebrid-docker-builds/AMD64_DONE"
          echo "${{ env.VERSION }}" > "$AMD64_FILE"
          echo "Marked AMD64 build as complete for version ${{ env.VERSION }}"
          
          # Log status for debugging
          if [ -f "$AMD64_FILE" ]; then
            echo "AMD64 status file exists and contains: $(cat $AMD64_FILE)"
          else
            echo "Failed to create AMD64 status file"
          fi
